// pages/Playbook.jsx
import React from 'react';
import PlaybookCard from '../components/PlaybookCard';
import { useTheme } from '../context/Themecontext';

const Playbook = () => {
  const { isDark } = useTheme();

  const playbookActions = {
    staffing: [
      {
        id: 1,
        title: "Increase Pulmonology Staff",
        description: "Add 3 pulmonologists to night shift rotation",
        priority: "high",
        status: "pending",
        impact: "High",
        effort: "Medium"
      },
      {
        id: 2,
        title: "Extend ICU Nurse Shifts",
        description: "Prepare for 20% increase in ICU admissions",
        priority: "high",
        status: "in-progress",
        impact: "High",
        effort: "Low"
      },
      {
        id: 3,
        title: "Activate On-call Residents",
        description: "Notify backup medical residents for emergency coverage",
        priority: "medium",
        status: "pending",
        impact: "Medium",
        effort: "Low"
      }
    ],
    supplies: [
      {
        id: 1,
        title: "Stock Oxygen Cylinders",
        description: "Increase oxygen cylinder inventory by 40%",
        priority: "high",
        status: "completed",
        impact: "Critical",
        effort: "Medium"
      },
      {
        id: 2,
        title: "Order Respiratory Medications",
        description: "Pre-order bronchodilators and corticosteroids",
        priority: "high",
        status: "pending",
        impact: "High",
        effort: "Low"
      },
      {
        id: 3,
        title: "Prepare Ventilators",
        description: "Ensure 15 additional ventilators are ready",
        priority: "medium",
        status: "in-progress",
        impact: "Medium",
        effort: "High"
      }
    ],
    advisories: [
      {
        id: 1,
        title: "Public Health Advisory",
        description: "Send SMS alerts to senior citizens about air quality",
        priority: "medium",
        status: "pending",
        impact: "Medium",
        effort: "Low"
      },
      {
        id: 2,
        title: "Clinic Preparation Notice",
        description: "Notify outpatient clinics about expected surge",
        priority: "low",
        status: "completed",
        impact: "Low",
        effort: "Low"
      }
    ]
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className={`text-3xl font-bold transition-colors ${
            isDark ? 'text-white' : 'text-gray-800'
          }`}>
            AI Surge Response Playbook
          </h1>
          <p className={`transition-colors ${
            isDark ? 'text-gray-400' : 'text-gray-600'
          }`}>
            Automated action plan generated by CrewAI agent
          </p>
        </div>
        <button className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold transition-colors flex items-center space-x-2">
          <span>📄</span>
          <span>Export as PDF</span>
        </button>
      </div>

      {/* Playbook Generated Info */}
      <div className="bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-xl p-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold mb-2">Playbook Generated Successfully! 🎯</h2>
            <p className="opacity-90">AI agent has analyzed current conditions and prepared optimized response actions</p>
          </div>
          <div className="text-right">
            <p className="text-sm opacity-90">Generated: {new Date().toLocaleString()}</p>
            <p className="text-sm opacity-90">Surge Expected: 48 hours</p>
          </div>
        </div>
      </div>

      {/* Action Categories */}
      <div className="space-y-8">
        {/* Staffing Actions */}
        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className={`p-3 rounded-lg transition-colors ${
              isDark ? 'bg-green-900' : 'bg-green-100'
            }`}>
              <span className="text-2xl">👥</span>
            </div>
            <div>
              <h2 className={`text-2xl font-bold transition-colors ${
                isDark ? 'text-white' : 'text-gray-800'
              }`}>
                Staffing Recommendations
              </h2>
              <p className={`transition-colors ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}>
                Optimize medical staff allocation and scheduling
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {playbookActions.staffing.map(action => (
              <PlaybookCard key={action.id} {...action} />
            ))}
          </div>
        </div>

        {/* Supply Actions */}
        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className={`p-3 rounded-lg transition-colors ${
              isDark ? 'bg-orange-900' : 'bg-orange-100'
            }`}>
              <span className="text-2xl">📦</span>
            </div>
            <div>
              <h2 className={`text-2xl font-bold transition-colors ${
                isDark ? 'text-white' : 'text-gray-800'
              }`}>
                Supply Chain Actions
              </h2>
              <p className={`transition-colors ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}>
                Manage medical supplies and equipment inventory
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {playbookActions.supplies.map(action => (
              <PlaybookCard key={action.id} {...action} />
            ))}
          </div>
        </div>

        {/* Advisory Actions */}
        <div>
          <div className="flex items-center space-x-3 mb-4">
            <div className={`p-3 rounded-lg transition-colors ${
              isDark ? 'bg-blue-900' : 'bg-blue-100'
            }`}>
              <span className="text-2xl">📢</span>
            </div>
            <div>
              <h2 className={`text-2xl font-bold transition-colors ${
                isDark ? 'text-white' : 'text-gray-800'
              }`}>
                Patient Advisories
              </h2>
              <p className={`transition-colors ${
                isDark ? 'text-gray-400' : 'text-gray-600'
              }`}>
                Public health communications and alerts
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {playbookActions.advisories.map(action => (
              <PlaybookCard key={action.id} {...action} />
            ))}
          </div>
        </div>
      </div>

      {/* Playbook Summary */}
      <div className={`rounded-xl shadow-sm border p-6 transition-colors ${
        isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'
      }`}>
        <h3 className={`text-lg font-semibold mb-4 transition-colors ${
          isDark ? 'text-white' : 'text-gray-800'
        }`}>
          Playbook Summary
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-blue-900' : 'bg-blue-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-blue-300' : 'text-blue-600'
            }`}>
              8
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-blue-200' : 'text-blue-700'
            }`}>
              Total Actions
            </div>
          </div>
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-green-900' : 'bg-green-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-green-300' : 'text-green-600'
            }`}>
              2
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-green-200' : 'text-green-700'
            }`}>
              Completed
            </div>
          </div>
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-yellow-900' : 'bg-yellow-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-yellow-300' : 'text-yellow-600'
            }`}>
              3
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-yellow-200' : 'text-yellow-700'
            }`}>
              In Progress
            </div>
          </div>
          <div className={`p-4 rounded-lg text-center transition-colors ${
            isDark ? 'bg-gray-700' : 'bg-gray-50'
          }`}>
            <div className={`text-2xl font-bold transition-colors ${
              isDark ? 'text-gray-300' : 'text-gray-600'
            }`}>
              3
            </div>
            <div className={`text-sm transition-colors ${
              isDark ? 'text-gray-200' : 'text-gray-700'
            }`}>
              Pending
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Playbook;